### ISSUE TITLE
onAuthRequired event doesn't fire for requests sent from extension on MV3.

### ISSUE THREAD

**Issue by maximtop** [AdguardTeam/AdGuardVPNExtension#110]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN Browser Extension version

2.0.16

### Environment

```markdown
- OS: MacOS
- Browser: Chrome
```

### Issue Details

In the extension, we have implemented a mechanism that triggers the onAuthRequired event whenever the proxy settings are changed. 

https://github.com/AdguardTeam/AdGuardVPNExtension/blob/f2a4fad5291a5e7269531418aa0049acc2444988/src/background/proxy/chrome/proxyApi.ts#L139-L146

We created this mechanism to prevent situations where the onAuthRequired event doesn't fire for certain requests, such as those involving websockets. This works as expected in Manifest V2 (mv2), with the onAuthRequired event firing every time. However, in the extension built on Manifest V3 (mv3), it doesn't fire.

### Expected Behavior

The onAuthRequired event is designed to fire every time a request is sent via a proxy.

### Additional Information

chromium bug tracker
https://bugs.chromium.org/p/chromium/issues/detail?id=1464898

**Comment by alexx7311** [comment]
Here's the link on how to reproduce the problem https://github.com/AdguardTeam/AdGuardVPNExtension/issues/109

**Comment by ameshkov** [comment]
Since the old workaround works no more in MV3, we should try a different one now, even uglier than the old one:

```javascript
try {
	const ret = await chrome.windows.create({
		url: `http://${nanoid()}.${PAC_SCRIPT_CHECK_URL}`,
		focused: false,
		state: 'minimized',
	});
	await new Promise(resolve => setTimeout(resolve, 2000));
	await chrome.windows.remove(ret.id);
} catch (ex) {
	console.log(`Error while using the workaround to force onAuthRequired: ${ex}`);
}
```

**Comment by ihurin** [comment]
+1 CRM 779919.

**Comment by db-EV** [comment]
Same problem here, nearly unusable right now.

**Comment by AleksandrKalininAdGuard** [comment]
+3 CRM
781400
780089
781089

**Comment by AleksandrKalininAdGuard** [comment]
+1 CRM 781693

**Comment by ihurin** [comment]
+1 CRM 785031

**Comment by ihurin** [comment]
@maximtop hi, is there anything new regarding this?

**Comment by db-EV** [comment]
Was fixed in release 2.0.22 (https://github.com/AdguardTeam/AdGuardVPNExtension/releases/tag/v2.0.22).

**Comment by ihurin** [comment]
@db-EV hey, what if issue is still repro in the new version in Opera in Incognito mode? CRM 791374
